name       : cairomm
version    : 1.12.2
release    : 9
source     :
    - https://www.cairographics.org/releases/cairomm-1.12.2.tar.gz : 45c47fd4d0aa77464a75cdca011143fea3ef795c4753f6e860057da5fb8bd599
license    :
    - LGPL-2.0
summary    : C++ bindings to Cairo
description: |
    C++ bindings to Cairo
replaces   :
    - libcairomm
    - devel : libcairomm-devel
    - docs : libcairomm-docs
component  : desktop.library
optimize   : speed
builddeps  :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(cairo)
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib64/cairomm-1.0/include
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
