name        : cairomm
version     : 1.11.2
release     : 4
source      :
    - http://cairographics.org/releases/cairomm-1.11.2.tar.gz : ccf677098c1e08e189add0bd146f78498109f202575491a82f1815b6bc28008d
homepage    : http://cairographics.org
license     :
    - LGPL-2.0
summary     : C++ bindings to Cairo
builddeps   :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(cairo)
patterns    :
    - docs:
        - /usr/share/devhelp
        - /usr/share/doc
    - devel:
        - /usr/lib64/cairomm-1.0/include
replaces    :
    - libcairomm
    - devel: libcairomm-devel
    - docs: libcairomm-docs
description : |
    C++ bindings to Cairo
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
