name        : cairomm
version     : 1.12.0
release     : 6
source     :
    - http://cairographics.org/releases/cairomm-1.12.0.tar.gz : 50435aec6fdd976934b791e808993160113ad19ca53a5634a9b64ccbe55874cc
license     :
    - LGPL-2.0
summary     : C++ bindings to Cairo
builddeps   :
    - pkgconfig(glibmm-2.4)
    - pkgconfig(cairo)
patterns    :
    - docs:
        - /usr/share/devhelp
        - /usr/share/doc
    - devel:
        - /usr/lib64/cairomm-1.0/include
replaces    :
    - libcairomm
    - devel: libcairomm-devel
    - docs: libcairomm-docs
description : |
    C++ bindings to Cairo
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
