name       : cairomm
version    : 1.14.4
release    : 17
source     :
    - https://www.cairographics.org/releases/cairomm-1.14.4.tar.xz : 4749d25a2b2ef67cc0c014caaf5c87fa46792fc4b3ede186fb0fc932d2055158
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : C++ bindings to Cairo
description: |
    C++ bindings to Cairo
replaces   :
    - libcairomm
    - devel : libcairomm-devel
    - docs : libcairomm-docs
optimize   : speed
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glibmm-2.4)
    - doxygen
    - graphviz
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib64/cairomm-1.0/include
setup      : |
    %meson_configure -Dbuild-documentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install
